import React,{useEffect,useMemo,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowUpRight,Package,Boxes,ShoppingBag,Users,Upload,Plus,Trash2,Save,RefreshCw,LogOut} from 'lucide-react';
import {api,API_ORIGIN} from './lib/api';
import {useStore} from './store/store';

const money=n=>`₱${Number(n||0).toLocaleString('en-PH')}`;
const blank={name:'',slug:'',price:1490,compareAtPrice:'',category:'T-Shirts',collection:'CORE',description:'',shortDescription:'',colors:['Black'],sizes:['XS','S','M','L','XL','XXL'],material:'Premium cotton',fit:'Relaxed',care:'Machine wash cold. Do not bleach. Hang dry.',modelInfo:'Model is 183cm and wears size M.',tags:['monsz','everyday'],published:true,newArrival:false,bestSeller:false,featured:false,images:[],variants:[]};
const sizes=['XS','S','M','L','XL','XXL'];
const colors=['Black','White','Stone','Grey','Charcoal','Navy','Olive','Brown','Cream'];

function ensureVariants(p){
 const out=[];for(const c of p.colors||[])for(const s of p.sizes||[]){const old=(p.variants||[]).find(v=>v.color===c&&v.size===s);out.push(old||{sku:`MONSZ-${(p.slug||'PRODUCT').toUpperCase().replace(/[^A-Z0-9]+/g,'-')}-${c.slice(0,3).toUpperCase()}-${s}`,color:c,size:s,stock:0,price:Number(p.price)||0,image:''})}return out;
}

export default function Admin(){
 const user=useStore(s=>s.user),logout=useStore(s=>s.logout),nav=useNavigate();
 const [tab,setTab]=useState('dashboard'); const [stats,setStats]=useState(null); const [products,setProducts]=useState([]); const [inventory,setInventory]=useState([]); const [orders,setOrders]=useState([]); const [editing,setEditing]=useState(null); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(false);
 useEffect(()=>{if(!user||user.role!=='admin'){nav('/login');return}loadAll()},[user]);
 async function loadAll(){try{const [s,p,i,o]=await Promise.all([api('/admin/stats'),api('/admin/products'),api('/admin/inventory'),api('/admin/orders')]);setStats(s);setProducts(p);setInventory(i);setOrders(o)}catch(e){setNotice(e.message)}}
 if(!user||user.role!=='admin')return null;
 const tabs=[['dashboard','Dashboard'],['products','Products'],['inventory','Inventory'],['orders','Orders']];
 return <main className="adminPage">
   <div className="adminTop"><div><small>MONSZ / ADMIN</small><h1>CONTROL<br/>ROOM.</h1></div><div className="adminActions"><button onClick={()=>loadAll()}><RefreshCw size={15}/> REFRESH</button><Link to="/"><ArrowUpRight size={15}/> VIEW STORE</Link><button onClick={()=>{logout();nav('/login')}}><LogOut size={15}/> LOG OUT</button></div></div>
   <div className="adminTabs">{tabs.map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>{setTab(id);setEditing(null)}}>{label}</button>)}</div>
   {notice&&<div className="adminNotice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
   {tab==='dashboard'&&<Dashboard stats={stats} products={products} inventory={inventory}/>} 
   {tab==='products'&&<Products products={products} setProducts={setProducts} editing={editing} setEditing={setEditing} setNotice={setNotice} reload={loadAll}/>} 
   {tab==='inventory'&&<Inventory rows={inventory} reload={loadAll} setNotice={setNotice}/>} 
   {tab==='orders'&&<Orders orders={orders} reload={loadAll} setNotice={setNotice}/>} 
 </main>
}

function Dashboard({stats,products,inventory}){const low=inventory.filter(x=>x.stock<=5).slice(0,8);return <section className="adminSection"><div className="statGrid">{[['Products',stats?.products??0,Package],['Published',stats?.published??0,Boxes],['Customers',stats?.customers??0,Users],['Orders',stats?.orders??0,ShoppingBag],['Sales',money(stats?.sales??0),ArrowUpRight],['Low Stock',stats?.lowStock??0,Boxes]].map(([label,val,Icon])=><div className="statCard" key={label}><Icon size={18}/><small>{label}</small><strong>{val}</strong></div>)}</div><div className="adminColumns"><div className="panel"><div className="panelHead"><h2>RECENT PRODUCTS</h2><span>{products.length} total</span></div>{products.slice(0,8).map(p=><div className="adminRow" key={p._id}><span>{p.name}</span><span>{money(p.price)}</span><span>{p.published?'LIVE':'DRAFT'}</span></div>)}</div><div className="panel"><div className="panelHead"><h2>LOW STOCK</h2><span>≤ 5 units</span></div>{low.length?low.map(x=><div className="adminRow" key={x._id}><span>{x.product}</span><span>{x.color} / {x.size}</span><strong>{x.stock}</strong></div>):<p className="muted">No low-stock variants.</p>}</div></div></section>}

function Products({products,setProducts,editing,setEditing,setNotice,reload}){const [query,setQuery]=useState('');const list=products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));return <section className="adminSection"><div className="panelHead"><div><h2>PRODUCT MANAGEMENT</h2><span>Create, edit, publish and manage product variants.</span></div><button className="adminPrimary" onClick={()=>setEditing({...blank,slug:'',variants:ensureVariants(blank)})}><Plus size={15}/> NEW PRODUCT</button></div><div className="productAdminLayout"><div className="panel productList"><input className="adminSearch" placeholder="SEARCH PRODUCTS" value={query} onChange={e=>setQuery(e.target.value)}/>{list.map(p=><button className={'productAdminRow '+(editing?._id===p._id?'active':'')} key={p._id} onClick={()=>setEditing({...p,variants:p.variants||[]})}><span className="adminThumb">{p.images?.[0]?<img src={p.images[0].startsWith('http')?p.images[0]:API_ORIGIN+p.images[0]}/>:<span/>}</span><span><strong>{p.name}</strong><small>{p.category} · {p.published?'LIVE':'DRAFT'}</small></span><span>{money(p.price)}</span></button>)}</div><ProductEditor product={editing} setProduct={setEditing} setNotice={setNotice} reload={reload}/></div></section>}

function ProductEditor({product,setProduct,setNotice,reload}){const [files,setFiles]=useState([]);if(!product)return <div className="panel emptyAdmin"><Package size={30}/><h2>SELECT A PRODUCT</h2><p>Create a new product or select one from the list.</p></div>;
 const update=(k,v)=>setProduct({...product,[k]:v});
 function toggleArray(k,v){const arr=product[k]||[];update(k,arr.includes(v)?arr.filter(x=>x!==v):[...arr,v])}
 async function save(){try{setNotice('');const payload={...product,variants:ensureVariants(product)};let saved;if(product._id){saved=await api('/admin/products/'+product._id,{method:'PUT',body:JSON.stringify(payload)})}else{saved=await api('/admin/products',{method:'POST',body:JSON.stringify(payload)})}setProduct(saved);setNotice('Product saved.');reload()}catch(e){setNotice(e.message)}}
 async function remove(){if(!product._id)return;if(!confirm(`Delete ${product.name}?`))return;try{await api('/admin/products/'+product._id,{method:'DELETE'});setProduct(null);setNotice('Product deleted.');reload()}catch(e){setNotice(e.message)}}
 async function upload(){if(!product._id||!files.length)return setNotice('Save the product first, then upload images.');const fd=new FormData();files.forEach(f=>fd.append('images',f));try{const data=await api('/admin/products/'+product._id+'/images',{method:'POST',body:fd});setProduct(data.product);setFiles([]);setNotice('Images uploaded.')}catch(e){setNotice(e.message)}}
 async function deleteImage(url){try{const p=await api('/admin/products/'+product._id+'/images',{method:'DELETE',body:JSON.stringify({url})});setProduct(p)}catch(e){setNotice(e.message)}}
 return <div className="panel editor"><div className="panelHead"><div><h2>{product._id?'EDIT PRODUCT':'NEW PRODUCT'}</h2><span>{product._id||'Unsaved product'}</span></div><div className="editorButtons"><button className="adminPrimary" onClick={save}><Save size={15}/> SAVE</button>{product._id&&<button className="adminDanger" onClick={remove}><Trash2 size={15}/> DELETE</button>}</div></div>
 <div className="editorForm"><label>NAME<input value={product.name} onChange={e=>update('name',e.target.value)}/></label><label>SLUG<input value={product.slug} onChange={e=>update('slug',e.target.value)}/></label><div className="formGrid"><label>PRICE<input type="number" value={product.price} onChange={e=>update('price',Number(e.target.value))}/></label><label>COMPARE PRICE<input type="number" value={product.compareAtPrice||''} onChange={e=>update('compareAtPrice',e.target.value?Number(e.target.value):'')}/></label></div><div className="formGrid"><label>CATEGORY<select value={product.category} onChange={e=>update('category',e.target.value)}>{['T-Shirts','Shirts','Hoodies','Sweatshirts','Jackets','Pants','Shorts','Accessories'].map(x=><option key={x}>{x}</option>)}</select></label><label>COLLECTION<select value={product.collection} onChange={e=>update('collection',e.target.value)}>{['CORE','ESSENTIALS','MONSZ STUDIO','NEW ARRIVALS','SEASONAL','LIMITED'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>SHORT DESCRIPTION<input value={product.shortDescription||''} onChange={e=>update('shortDescription',e.target.value)}/></label><label>DESCRIPTION<textarea rows="5" value={product.description||''} onChange={e=>update('description',e.target.value)}/></label><div><span className="fieldLabel">COLORS</span><div className="chips">{colors.map(c=><button type="button" className={product.colors?.includes(c)?'chip active':''} key={c} onClick={()=>toggleArray('colors',c)}>{c}</button>)}</div></div><div><span className="fieldLabel">SIZES</span><div className="chips">{sizes.map(s=><button type="button" className={product.sizes?.includes(s)?'chip active':''} key={s} onClick={()=>toggleArray('sizes',s)}>{s}</button>)}</div></div><div className="formGrid"><label>MATERIAL<input value={product.material||''} onChange={e=>update('material',e.target.value)}/></label><label>FIT<input value={product.fit||''} onChange={e=>update('fit',e.target.value)}/></label></div><label>MODEL INFO<input value={product.modelInfo||''} onChange={e=>update('modelInfo',e.target.value)}/></label><label>CARE<textarea rows="3" value={product.care||''} onChange={e=>update('care',e.target.value)}/></label><div className="toggles">{[['published','Published'],['newArrival','New Arrival'],['bestSeller','Best Seller'],['featured','Featured']].map(([k,l])=><label key={k}><input type="checkbox" checked={!!product[k]} onChange={e=>update(k,e.target.checked)}/>{l}</label>)}</div></div>
 <div className="imageManager"><div className="panelHead"><div><h3>PRODUCT IMAGES</h3><span>JPG, PNG, WEBP or AVIF · max 8MB each</span></div><label className="uploadButton"><Upload size={15}/> SELECT FILES<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple onChange={e=>setFiles([...e.target.files])}/></label></div>{files.length>0&&<div className="uploadQueue">{files.map(f=><span key={f.name}>{f.name}</span>)}<button className="adminPrimary" onClick={upload}>UPLOAD <Upload size={14}/></button></div>}<div className="imageGrid">{(product.images||[]).map(url=><div className="imageAdmin" key={url}><img src={url.startsWith('http')?url:API_ORIGIN+url}/><button onClick={()=>deleteImage(url)}><Trash2 size={14}/></button></div>)}</div></div>
 <div className="variantManager"><div className="panelHead"><div><h3>VARIANTS & INVENTORY</h3><span>Stock is managed independently per color and size.</span></div></div><div className="variantTable"><div className="variantHead"><span>SKU</span><span>COLOR</span><span>SIZE</span><span>PRICE</span><span>STOCK</span></div>{ensureVariants(product).map((v,i)=><div className="variantRow" key={v.sku}><span>{v.sku}</span><span>{v.color}</span><span>{v.size}</span><input type="number" value={v.price??product.price} onChange={e=>{const vs=ensureVariants(product);vs[i]={...v,price:Number(e.target.value)};update('variants',vs)}}/><input type="number" min="0" value={v.stock??0} onChange={e=>{const vs=ensureVariants(product);vs[i]={...v,stock:Math.max(0,Number(e.target.value))};update('variants',vs)}}/></div>)}</div></div>
 </div>}

function Inventory({rows,reload,setNotice}){const [search,setSearch]=useState('');const [local,setLocal]=useState({});const list=rows.filter(x=>(x.product+' '+x.sku+' '+x.color+' '+x.size).toLowerCase().includes(search.toLowerCase()));async function save(r){try{await api('/admin/inventory',{method:'PATCH',body:JSON.stringify({productId:r.productId,sku:r.sku,stock:Number(local[r.sku]??r.stock)})});setNotice(`${r.sku} updated.`);reload()}catch(e){setNotice(e.message)}}return <section className="adminSection"><div className="panelHead"><div><h2>INVENTORY MANAGEMENT</h2><span>Update stock at the SKU level.</span></div><input className="adminSearch compact" placeholder="SEARCH SKU / PRODUCT" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="panel inventoryPanel"><div className="inventoryHead"><span>PRODUCT</span><span>VARIANT</span><span>SKU</span><span>STOCK</span><span>ACTION</span></div>{list.map(r=><div className={'inventoryRow '+(r.stock<=5?'low':'')} key={r._id}><span>{r.product}</span><span>{r.color} / {r.size}</span><span>{r.sku}</span><span><input type="number" min="0" value={local[r.sku]??r.stock} onChange={e=>setLocal({...local,[r.sku]:e.target.value})}/></span><button onClick={()=>save(r)}><Save size={14}/> SAVE</button></div>)}</div></section>}

function Orders({orders,reload,setNotice}){async function update(id,status){try{await api('/admin/orders/'+id,{method:'PATCH',body:JSON.stringify({status})});setNotice('Order updated.');reload()}catch(e){setNotice(e.message)}}return <section className="adminSection"><div className="panelHead"><div><h2>ORDERS</h2><span>Manage fulfilment status.</span></div></div><div className="panel inventoryPanel"><div className="inventoryHead"><span>ORDER</span><span>CUSTOMER</span><span>TOTAL</span><span>PAYMENT</span><span>STATUS</span></div>{orders.map(o=><div className="inventoryRow" key={o._id}><span>#{o._id.slice(-8).toUpperCase()}</span><span>{o.user?.name||o.email||'Guest'}</span><span>{money(o.total)}</span><span>{o.paymentMethod||'—'}</span><select value={o.status} onChange={e=>update(o._id,e.target.value)}>{['Pending','Confirmed','Processing','Packed','Shipped','Out for Delivery','Delivered','Cancelled','Refunded'].map(x=><option key={x}>{x}</option>)}</select></div>)}</div></section>}
